#!/usr/bin/bash
TITLE="NRSC-5 - HD Radio"

DEMO=fm
FREQ=978000000
RATE=2083334
GAIN=48
PROGRAM=0
REC=off
DESCRAM=off

OPTIONS="FREQ RATE GAIN PROGRAM REC"

function run {
  COMMAND="demodulators/${RT_DEMO} | "
  test -f ./descramblers/${RT_DESCRAM} && COMMAND="${COMMAND} ./descramblers/${RT_DESCRAM} $PRESET | "
  (test ! -z $RT_REC && test $RT_REC == "on") && COMMAND="${COMMAND} tee rec/$(echo $TITLE|cut -d" " -f1|tr 'A-Z' 'a-z')-$(date +%F-%H-%M-%S).${RT_DEMO} | "
  COMMAND="${COMMAND} ./bin/nrsc5 -r - $PROGRAM || (tput setaf 1 ; echo Failed ; tput sgr0)"
  tput setaf 4 ; echo "Running command:"
  echo $COMMAND ; tput sgr0
  eval $COMMAND
}
