#!/usr/bin/bash
TITLE="rtl_433 - decode radio transmissions from devices on the ISM bands"

DEMO=sdr
FREQ=433920000
RATE=250000
GAIN=automatic
REC=off
DESCRAM=off

OPTIONS="FREQ RATE GAIN REC"

function run {
  COMMAND="demodulators/${RT_DEMO} | "
  test -f ./descramblers/${RT_DESCRAM} && COMMAND="${COMMAND} ./descramblers/${RT_DESCRAM} $PRESET | "
  (test ! -z $RT_REC && test $RT_REC == "on") && COMMAND="${COMMAND} tee rec/$(echo $TITLE|cut -d" " -f1|tr 'A-Z' 'a-z')-$(date +%F-%H-%M-%S).${RT_DEMO} | "
    # TODO: Check 2>&1
  COMMAND="${COMMAND} ./bin/rtl_433 -r - 2>&1 || (tput setaf 1 ; echo Failed ; tput sgr0)"
  tput setaf 4 ; echo "Running command:"
  echo $COMMAND ; tput sgr0
  eval $COMMAND
# ./bin/rtl_433 -s $RT_RATE -r - -R1 -R2 -R3 -R4 -R6 -R7 -R8 -R10 -R11 -R12 -R13 -R14 -R15 -R16 -R17 -R18 -R19 -R20 -R21 -R22 -R23 -R24 -R25 -R26 -R29 -R30 -R31 -R32 -R33 -R34 -R35 -R36 -R37 -R38 -R39 -R40 -R41 -R42 -R43 -R44 -R45 -R46 -R47 -R48 -R49 -R50 -R51 -R52 -R53 -R54 -R55 -R56 -R57 -R58 -R59 -R60 -R61 -R62 -R63 -R64 -R67 -R68 -R69 -R70 -R71 -R72 -R73 -R74 -R75 -R76 -R77 -R78 -R79 -R80 -R81 -R82 -R83 -R84 -R85 -R86 -R87 -R88 -R89 -R90 -R91 -R92 -R93 -R94 -R95 -R96 -R97 -R98 -R99 -R100 -R101 -R102 -R103 -R104 -R105 -R106 -R107 -R108 -R109 -R110 -R111 -R112 -R113 -R114 -R115 -R116 -R117 -R118 -R119 -R120 -R121 -R122 -R123 -R124 -R125 -R126 -R127 -R128 -R129 -R130 -R131 -R132 -R133 -R134 -R135 -R136 -R137 -R138 -R139 -R140 -R141 -R142 -R143 -R144 -R145 -R146 -R147 -R148 -R149 -R150 2>&1 || (tput setaf 1 ; echo Failed ; tput sgr0)
}

